# Generated by Django 5.2.4 on 2025-07-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleName', models.CharField(max_length=100)),
                ('eventType', models.CharField(max_length=100)),
                ('serviceName', models.CharField(max_length=100)),
                ('threshold', models.IntegerField()),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(max_length=100)),
                ('serviceName', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('level', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
